# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-57a4793f-169b-4d59-bac3-ec1f8a2d191e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-57a4793f-169b-4d59-bac3-ec1f8a2d191e".device = "/dev/disk/by-uuid/57a4793f-169b-4d59-bac3-ec1f8a2d191e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3E9E-598B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3815679e-a773-4c82-be2c-ca08327105af"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
